apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: eventsource-webhook
spec:
  service:
    name: webhook
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    terraform:
      port: "12000"
      endpoint: /terraform
      method: POST


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-ingress
spec:
  ingressClassName: public
  rules:
    - host: webhook.local.naim.run
      http:
        paths:
          - path: /terraform
            pathType: Prefix
            backend:
              service:
                name: eventsource-webhook-eventsource-svc
                port:
                  number: 12000
